from .alg_duplicate_nodes import DuplicateNodes
from .alg_missing_nodes import MissingNodes
from .alg_orphan_nodes import OrphanNodes
from .alg_pipes_treatment_to_reservoir import PipesTreatmentToReservoir
from .alg_pipes_water_intake_to_treatment import PipesWaterIntakeToTreatment
